enableInlineHunks: true

enableMessageNames: false

initScope: peacockproject

nodeLinker: node-modules

packageExtensions:
    express@*:
        dependencies:
            mime: 1.6.0

plugins:
    -   path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
        spec: "https://mskelton.dev/yarn-outdated/v2"
    -   path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
        spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
